load_col:
  inter: [user_id, item_id, rating]
ITEM_ID_FIELD: item_id
RATING_FIELD: rating

user_inter_num_interval: "[15,inf)"
item_inter_num_interval: "[15,inf)"
val_interval:
  rating: "[3,inf)"

embedding_size: 64
n_layers: 3

learner: adam
learning_rate: 1e-3
reg_weight: 1e-4

ssl_temp: 0.1
alpha: 0.5
beta: 0.5
gamma: 0.5
ssl_reg_alpha: 1e-5
ssl_reg_beta: 1e-5
ssl_reg_gamma: 1e-6

show_progress: False
gpu_id: 0


